# Generated by Django 4.1.5 on 2023-02-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('style', models.CharField(choices=[('캐주얼', '캐주얼'), ('클래식', '클래식'), ('빈티지', '빈티지'), ('스트릿', '스트릿'), ('스포티', '스포티'), ('모던', '모던'), ('댄디', '댄디'), ('미니멀', '미니멀'), ('레이어드', '레이어드'), ('논코어', '논코어'), ('페미닌', '페미닌'), ('맥시멀', '맥시멀'), ('아메리칸 캐주얼', '아메리칸 캐주얼'), ('에스닉', '에스닉'), ('아방가르드', '아방가르드')], max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('season', models.CharField(choices=[('봄', '봄'), ('여름', '여름'), ('가을', '가을'), ('겨울', '겨울')], max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('clothes', models.ManyToManyField(blank=True, related_name='in_outfit', to='clothes.clothes')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_outfit', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='outfit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
