# Generated by Django 4.1.5 on 2023-01-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0003_remove_clothes_clothes_id_clothes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True)),
                ('temperature', models.IntegerField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('clothes', models.ManyToManyField(blank=True, to='clothes.clothes')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
