# Generated by Django 4.1.5 on 2023-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_outfit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='temperature',
        ),
        migrations.AddField(
            model_name='outfit',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall'), ('winter', 'winter')], max_length=25),
        ),
    ]
