# Generated by Django 4.0.1 on 2023-02-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_clothes_image'),
        ('outfits', '0003_remove_outfit_temperature_outfit_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='clothes',
            field=models.ManyToManyField(blank=True, to='clothes.Clothes'),
        ),
    ]
