# Generated by Django 4.1.5 on 2023-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_remove_outfit_temperature_outfit_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='season',
            field=models.CharField(choices=[('봄', '봄'), ('여름', '여름'), ('가을', '가을'), ('겨울', '겨울')], max_length=25),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='style',
            field=models.CharField(choices=[('캐주얼', '캐주얼'), ('클래식', '클래식'), ('빈티지', '빈티지'), ('스트릿', '스트릿'), ('스포티', '스포티'), ('모던', '모던'), ('댄디', '댄디'), ('미니멀', '미니멀'), ('레이어드', '레이어드'), ('논코어', '논코어'), ('페미닌', '페미닌'), ('맥시멀', '맥시멀'), ('아메리칸 캐주얼', '아메리칸 캐주얼'), ('에스닉', '에스닉'), ('아방가르드', '아방가르드')], max_length=255),
        ),
    ]
