# Generated by Django 4.1.5 on 2023-02-16 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_clothes_fit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0004_alter_outfit_image_alter_outfit_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='clothes',
            field=models.ManyToManyField(blank=True, related_name='in_outfit', to='clothes.clothes'),
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='likes',
        ),
        migrations.AddField(
            model_name='outfit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_outfit', to=settings.AUTH_USER_MODEL),
        ),
    ]
