# Generated by Django 4.1.5 on 2023-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_alter_outfit_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='season',
            field=models.CharField(blank=True, choices=[('봄', '봄'), ('여름', '여름'), ('가을', '가을'), ('겨울', '겨울')], max_length=25),
        ),
    ]
