# Generated by Django 4.1.5 on 2023-02-16 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0008_remove_clothes_likes_alter_clothes_major_category_and_more'),
        ('outfits', '0004_alter_outfit_image_alter_outfit_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='clothes',
            field=models.ManyToManyField(blank=True, related_name='in_outfit', to='clothes.clothes'),
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='likes',
        ),
        migrations.AlterField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='outfit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_outfit', to=settings.AUTH_USER_MODEL),
        ),
    ]
