# Generated by Django 4.1.5 on 2023-02-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_alter_outfit_image_alter_outfit_season_and_more'),
        ('outfits', '0005_alter_outfit_season'),
    ]

    operations = [
    ]
