# Generated by Django 4.1.5 on 2023-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='major_category',
            field=models.CharField(choices=[('top', '상의'), ('bottoms', '하의'), ('shoes', '신발'), ('accessory', '액세서리'), ('others', '기타')], max_length=255),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=255),
        ),
    ]
