# Generated by Django 4.1.5 on 2023-01-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_major_category_alter_clothes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='clothes_id',
        ),
        migrations.AddField(
            model_name='clothes',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
