# Generated by Django 4.1.5 on 2023-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_majorcategory_minorcategory_clothes_minor_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
