# Generated by Django 4.1.5 on 2023-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_clothes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='fit',
            field=models.CharField(blank=True, choices=[('S', '슬림핏'), ('R', '레귤러핏'), ('O', '오버핏')], max_length=255),
        ),
    ]
