# Generated by Django 4.1.5 on 2023-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_clothes_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='fit',
            field=models.CharField(blank=True, choices=[('슬림핏', '슬림핏'), ('레귤러핏', '레귤러핏'), ('오버핏', '오버핏')], max_length=255),
        ),
    ]
